/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        app: {
          50: "#ECFDFE",
          100: "#D4FBFC",
          200: "#AEF7FA",
          300: "#83F3F7",
          400: "#58EFF4",
          500: "#2FE9F1",
          600: "#0ED0D7",
          700: "#0B9DA2",
          800: "#076A6E",
          900: "#043335",
          950: "#021C1D",
          success: "#2FE9F1",
          warning: {
            50: "#FEFBEB",
            100: "#FEF8D8",
            200: "#FCF2B5",
            300: "#FBEA8E",
            400: "#F9E46C",
            500: "#F8DD45",
            600: "#F6D209",
            700: "#B69C07",
            800: "#7B6905",
            900: "#3B3202",
            950: "#1D1901",
          },
          error: {
            50: "#FFEBEB",
            100: "#FED7D7",
            200: "#FEAFAF",
            300: "#FD8686",
            400: "#FD5959",
            500: "#FC3232",
            600: "#EC0303",
            700: "#B50303",
            800: "#790202",
            900: "#3C0101",
            950: "#1E0000",
          },
        },
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
